import CSSimg from "/assets/images/B_W_CSS.png";
import HTMLimg from "/assets/images/B_W_HTML.png";
import JSimg from "/assets/images/B_W_JS.png";
import REACTimg from "/assets/images/B_W_React.png";
import Wordpressimg from "/assets/images/B_W_Wordpress.png";
import GSAPimg from "/assets/images/B_W_GSAP.png";
import RIVLMEDIAMOCKUPimg from "/assets/images/RIVLMEDIA_Mockupv2WEBP.webp";
import APPLEMOCKUPimg from "/assets/images/Apple_MockupWEBP.webp";
import OnlineIDMOCKUPimg from "/assets/images/OnlineID_Mockupv2WEBP.webp";
import JavascriptMOCKUPimg from "/assets/images/Javascript_Gamev3WEBP.webp";
import FILMREVIEWMOCKUPimg from "/assets/images/FilmReview_MockupWEBP.webp";
import PFimg from "/assets/images/Rick_Zwitserland.png";
import RIVLMediaBanner from "/assets/images/HomeScreen_RIVL_Media_v2.png";
import RIVLMediaSEO from "/assets/images/RIVLMedia_SEO_Score.png";
import ComputerEquipment from "/assets/images/Computer-Equipment.jpg";
import Hyoimg from "/assets/images/Hyo.jpg";
import YooAhimg from "/assets/images/YooAh.webp";
import Joyimg from "/assets/images/Joy.jpg";
import Boraimg from "/assets/images/Bora.jpg";
import Itzyimg from "/assets/images/Itzy.jpg";

export const CSSIMG = CSSimg;
export const HTMLIMG = HTMLimg;
export const JSIMG = JSimg;
export const REACTIMG = REACTimg;
export const WORDIMG = Wordpressimg;
export const GSAPIMG = GSAPimg;
export const RIVLMEDIAMOCKUPIMG = RIVLMEDIAMOCKUPimg;
export const APPLEMOCKUPIMG = APPLEMOCKUPimg;
export const JAVASCRIPTMOCKUPIMG = JavascriptMOCKUPimg;
export const FILMREVIEWMOCKUPIMG = FILMREVIEWMOCKUPimg;
export const ONLINEIDMOCKUPIMG = OnlineIDMOCKUPimg;
export const PFIMG = PFimg;
export const RIVLMEDIABANNERIMG = RIVLMediaBanner;
export const RIVLMEDIASEOIMG = RIVLMediaSEO;
export const COMPEQUIPIMG = ComputerEquipment;
export const HYOIMG = Hyoimg;
export const YOOAHIMG = YooAhimg;
export const JOYIMG = Joyimg;
export const BORAIMG = Boraimg;
export const ITZYIMG = Itzyimg;